apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  ATLAS_URI: bW9uZ29kYjovL21vbmdvOjI3MDE3L2Jsb2dfbWVybg==
  HASH_KEY: dGhpc0lzTXlIYXNoS2V5Cg==           
  JWT_SECRET_KEY: dGhpc0lzTXlKd3RTZWNyZXRLZXkK
  PORT: MzAwMA==