apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  ATLAS_URI: {{ .Values.secrets.ATLAS_URI }}
  HASH_KEY: {{ .Values.secrets.HASH_KEY }}
  JWT_SECRET_KEY: {{ .Values.secrets.JWT_SECRET_KEY }}
  PORT: {{ .Values.secrets.PORT }}
